version: '3'
services:
  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: cool-password
      POSTGRES_USER: cool-user
      POSTGRES_DB: cool-database
  platform:
    image: node:carbon
    command: yarn start
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
